# Generated by Django 5.2.5 on 2025-11-20 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('ENCERRADO', 'Encerrado')], default='ABERTO', max_length=20)),
                ('categoria', models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('REDE', 'Rede'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='BAIXA', max_length=10)),
                ('sugestao_ia', models.TextField(blank=True, null=True, verbose_name='Sugestão da IA')),
                ('solucao_tecnico', models.TextField(blank=True, null=True, verbose_name='Solução Final')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados_criados', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atendidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prioridade', '-data_abertura'],
            },
        ),
    ]
